name: Test DAGs

on:
  push:
    paths:
      - 'dags/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip check
#     - name: Lint DAGs with Flake8
#       run: |
#         pip install flake8==4.0.1
#         flake8 --ignore E501 dags --benchmark -v
#     - name: Confirm Black code compliance fo DAGs
#       run: |
#         pip install pytest-black==0.3.12
#         pytest dags --black -v
    - name: 'Test Airflow DAGs'
  uses: micael-grilo/airflow-dags-test-action@v2.2.2
    with:
      requirements-file: project/requirements.txt
      dags-path: project/dags
      dags-test-folder: project/tests
      var-file: project/var.json
